/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fanyuanhua_ndkdemo_tool_FFmpegCmd */

#ifndef _Included_com_example_fanyuanhua_ndkdemo_tool_FFmpegCmd
#define _Included_com_example_fanyuanhua_ndkdemo_tool_FFmpegCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fanyuanhua_ndkdemo_tool_FFmpegCmd
 * Method:    stringFormJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fanyuanhua_ndkdemo_tool_FFmpegCmd_stringFormJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
